<a target="_blank" href="https://colab.research.google.com/github/Saleh6233/pushTutorial/blob/master/assignment2.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Write a python multi-threaded code to perform few different tasks

In [3]:
import threading
import time
import numpy as np

### Task 1 : creating some random integer array ranging from 1 to 100

In [5]:
def random_integer():
    for i in range(1,4):
        x = np.random.randint(100, size=(i,3))
        print(f"Some random integer array: {x}")
        time.sleep(0.5)

### Task 2 : creating some random float array ranging from 0 to 1

In [7]:
def random_float():
    for i in range(1,4):
        x = np.random.rand(i,3)
        print(f"Some random float array: {x}")
        time.sleep(0.5)

### Task 3 : creating some linearly spaced array ranging from 1 to 100

In [9]:
def random_linspace():
    for i in range(1,4):
        y = np.linspace(0., 1., i*2).reshape(i,2)
        print(f"Some linearly spaced array: {y}")
        time.sleep(0.5)

## Running functions without threads

In [11]:
time1 = time.perf_counter()

random_integer()
random_float()
random_linspace()

time2 = time.perf_counter()

print(f"Total time taken = {time2-time1}")

Some random integer array: [[70 67 19]]
Some random integer array: [[56 60 90]
 [45 30 59]]
Some random integer array: [[72 15 79]
 [62 91 17]
 [56 70 92]]
Some random float array: [[0.44928983 0.95437096 0.02365036]]
Some random float array: [[0.10976217 0.00829449 0.28531283]
 [0.04326684 0.17285955 0.71038295]]
Some random float array: [[0.12863895 0.88407697 0.93259313]
 [0.98292441 0.63154325 0.78653256]
 [0.10182988 0.77878515 0.66356776]]
Some linearly spaced array: [[0. 1.]]
Some linearly spaced array: [[0.         0.33333333]
 [0.66666667 1.        ]]
Some linearly spaced array: [[0.  0.2]
 [0.4 0.6]
 [0.8 1. ]]
Total time taken = 4.511136400000396


## Running functions with threads

In [13]:
time1 = time.perf_counter()

t1 = threading.Thread(target=random_integer)
t2 = threading.Thread(target=random_float)
t3 = threading.Thread(target=random_linspace)


t1.start()
t2.start()
t3.start()


t1.join()
t2.join()
t3.join()

time2 = time.perf_counter()

print(f"Total time taken = {time2-time1}")

Some random integer array: [[93 42  6]]
Some random float array: [[0.26214932 0.28318159 0.81024796]]
Some linearly spaced array: [[0. 1.]]
Some random integer array: [[63 37 94]
 [52 96 66]]
Some random float array: [[0.08317299 0.08550786 0.53431995]
 [0.56486495 0.78261221 0.80647069]]
Some linearly spaced array: [[0.         0.33333333]
 [0.66666667 1.        ]]
Some random integer array: [[17 46 79]
 [88 94 62]
 [91 47 55]]
Some random float array: [[0.4408592  0.62616891 0.88427486]
 [0.12970867 0.6017217  0.54299827]
 [0.80602535 0.3223929  0.77141491]]
Some linearly spaced array: [[0.  0.2]
 [0.4 0.6]
 [0.8 1. ]]
Total time taken = 1.5083439000009093
