<a target="_blank" href="https://colab.research.google.com/github/Saleh6233/pushTutorial/blob/master/assignment2.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Write a python multi-threaded code to perform few different tasks

In [3]:
import threading
import time
import numpy as np

### Task 1 : creating some random integer array ranging from 1 to 100

In [5]:
def random_integer():
    for i in range(1,4):
        x = np.random.randint(100, size=(i,3))
        print(f"Some random integer array: {x}")
        time.sleep(0.5)

### Task 2 : creating some random float array ranging from 0 to 1

In [7]:
def random_float():
    for i in range(1,4):
        x = np.random.rand(i,3)
        print(f"Some random float array: {x}")
        time.sleep(0.5)

### Task 3 : creating some linearly spaced array ranging from 1 to 100

In [9]:
def random_linspace():
    for i in range(1,4):
        y = np.linspace(0., 1., i*2).reshape(i,2)
        print(f"Some linearly spaced array: {y}")
        time.sleep(0.5)

## Creating and joinng all threads

In [11]:
t1 = threading.Thread(target=random_integer)
t2 = threading.Thread(target=random_float)
t3 = threading.Thread(target=random_linspace)


t1.start()
t2.start()
t3.start()


t1.join()
t2.join()
t3.join()

print("All tasks completed.")

Some random integer array: [[10 85 72]]
Some random float array: [[0.54328319 0.55557182 0.82561186]]
Some linearly spaced array: [[0. 1.]]
Some random integer array: [[56 59 25]
 [96 13 13]]Some random float array: [[0.17895782 0.03222834 0.88652966]
 [0.80589309 0.05551978 0.38979546]]

Some linearly spaced array: [[0.         0.33333333]
 [0.66666667 1.        ]]
Some random float array: [[0.09313128 0.63043081 0.60905924]
 [0.70199708 0.61927491 0.77079877]
 [0.57683375 0.55791999 0.82933005]]
Some linearly spaced array: [[0.  0.2]
 [0.4 0.6]
 [0.8 1. ]]
Some random integer array: [[75 36 92]
 [30 54 28]
 [30 68  4]]
All tasks completed.
